version: '3.8'

services:
  weather_bot:
    build: .
    container_name: weather_tg_bot
    ports:
      - 8080:8080
    environment:
      - TOKEN=${TOKEN}
      - API_KEY=${API_KEY}
    restart: unless-stopped

    command: python main.py

