# Этап 1: Сборка зависимостей
FROM python:3.11-alpine AS builder


#ARG API_KEY
#ARG APP_DOMAIN
#ARG GET_PASSWORD
#ARG GET_USER
#ARG GF_SECURITY_ADMIN_PASSWORD
#ARG GF_SECURITY_ADMIN_USER
#ARG NGROK_AUTHTOKEN
#ARG POOL_HOST_DB
#ARG POSTGRES_DB
#ARG POSTGRES_PASSWORD
#ARG POSTGRES_USER
#ARG SECRET_TOKEN_TG_WEBHOOK
#ARG TG_BOT_API_URL
#ARG TOKEN

ENV API_KEY=${API_KEY}
ENV APP_DOMAIN=${APP_DOMAIN}
ENV GET_PASSWORD=${GET_PASSWORD}
ENV GET_USER=${GET_USER}
ENV GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
ENV GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
ENV NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
ENV POOL_HOST_DB=${POOL_HOST_DB}
ENV POSTGRES_DB=${POSTGRES_DB}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
ENV POSTGRES_USER=${POSTGRES_USER}
ENV SECRET_TOKEN_TG_WEBHOOK=${SECRET_TOKEN_TG_WEBHOOK}
ENV TG_BOT_API_URL=${TG_BOT_API_URL}
ENV TOKEN=${TOKEN}


WORKDIR /app
COPY . /app
#COPY ../.env /.env
RUN pip install --timeout=120 pipenv
RUN pipenv install --system

#CMD ["python", "-m", "src.app"]