global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'docker'
    dns_sd_configs:
      - names:
          - tasks.web
        type: 'A'
        port: 8888
    relabel_configs:
      - source_labels: [__meta_dns_name]
        regex: 'tasks.web'
        target_label: 'instance'
    scrape_interval: 10s