name: CI/CD Pipeline

on:
  push:
    branches:
      - async_tg_bot

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run unit tests
        run: |
          pipenv run pytest postgres/tests

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker buildx create --name mybuilder --use
          docker buildx inspect mybuilder --bootstrap
          docker buildx build \
            --push \
            -t ${{ secrets.DOCKER_USERNAME }}/weather_bot:latest \
            .
          docker images # Показываем все образы
          docker images ${{ secrets.DOCKER_USERNAME }}/weather_bot:latest